name: Delete Artifact

on:
  workflow_call:
    inputs:
      tfplan-artifact-id:
        description: 'Terraform Plan Artifact ID'
        required: true
        type: string
      github-repository:
        description: 'GitHub Repository'
        required: true
        type: string
    secrets:
      GITHUB_TOKEN_INPUT:
        description: 'GitHub Token'
        required: true

jobs:
  delete-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Delete Artifact
        run: |
          echo "Deleting Artifact ${{ inputs.tfplan-artifact-id }} from ${{ inputs.github-repository }}"
          curl -sL \
            -X DELETE \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN_INPUT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ inputs.github-repository }}/actions/artifacts/${{ inputs.tfplan-artifact-id }} && \
            echo "Artifact ${{ inputs.tfplan-artifact-id }} deleted from ${{ inputs.github-repository }}"