name: Dispatch Terraform CI/CD

on:
  workflow_dispatch:
    inputs:
      trigger_cd:
        description: 'Trigger CD'
        required: false
        type: boolean
        default: false
      environment:
        description: 'Environment'
        required: true
        type: choice
        options:
          - dev

jobs: 
  terraform-ci:
    uses: missaelcorm-iteso/schedulesync-aws/.github/workflows/terraform-ci.yml@main
    with:
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      working-directory: "environments/${{ github.event.inputs.environment }}"

  terraform-cd:
    if: ${{ github.event.inputs.trigger_cd == 'true' }}
    uses: missaelcorm-iteso/schedulesync-aws/.github/workflows/terraform-cd.yml@main
    with:
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      working-directory: "environments/${{ github.event.inputs.environment }}"