name: Dispatch Terraform CI/CD

on:
  workflow_dispatch:
    inputs:
      trigger_cd:
        description: 'Trigger CD'
        required: false
        type: boolean
        default: false
      environment:
        description: 'Environment'
        required: true
        type: choice
        options:
          - dev

jobs: 
  terraform-ci:
    uses: missaelcorm-iteso/schedulesync-aws/.github/workflows/terraform-ci.yml@add-sec-artifacts
    with:
      working-directory: "environments/${{ github.event.inputs.environment }}"
    secrets:
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}

  terraform-sec-scan:
    needs: terraform-ci
    uses: missaelcorm-iteso/schedulesync-aws/.github/workflows/terraform-sec-scan.yml@add-sec-artifacts
    with:
      working-directory: "environments/${{ github.event.inputs.environment }}"

  terraform-cd:
    needs: terraform-ci
    if: ${{ github.event.inputs.trigger_cd == 'true' }}
    uses: missaelcorm-iteso/schedulesync-aws/.github/workflows/terraform-cd.yml@main
    with:
      working-directory: "environments/${{ github.event.inputs.environment }}"
    secrets:
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}

  delete-artifact:
    needs: [terraform-ci, terraform-cd]
    if: ${{ always() }}
    uses: missaelcorm-iteso/schedulesync-aws/.github/workflows/delete-artifact.yml@main
    with:
      tfplan-artifact-id: ${{ needs.terraform-ci.outputs.tfplan-artifact-id }}
      github-repository: ${{ github.repository }}
    secrets:
      GITHUB_TOKEN_INPUT: ${{ secrets.GITHUB_TOKEN }}