name: Terraform CI

on:
  workflow_dispatch:
    inputs:
      trigger_cd:
        description: 'Trigger CD'
        required: false
        type: boolean
        default: false

jobs:
  terraform-ci:
    runs-on: ubuntu-latest
    container: "missaelcorm/terratool:v0.10"
    env:
      TF_LOG: INFO
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Terraform Init
        id: init
        working-directory: ${{ github.workspace }}/environments/dev
        run: |
          terraform init -input=false
          
      - name: Terraform Format
        id: fmt
        working-directory: ${{ github.workspace }}/environments/dev
        run: |
          terraform fmt -check=true -diff=true
        continue-on-error: true
      
      - name: Terraform Lint
        id: lint
        run: |
          tflint --init
          tflint --recursive --config $(pwd)/.tflint.hcl 

      - name: Terraform Validate
        id: validate
        working-directory: ${{ github.workspace }}/environments/dev
        run: |
          terraform validate

      - name: Terraform Security Check
        id: tfsec
        run: |
          tfsec ${{ github.workspace }}/environments/dev

      - name: Terraform Plan
        id: plan
        working-directory: ${{ github.workspace }}/environments/dev
        run: |
          terraform plan -input=false -compact-warnings -out=plan.file
      
      - name: Terraform Apply
        id: apply
        if: ${{ github.event.inputs.trigger_cd == true }}
        working-directory: ${{ github.workspace }}/environments/dev
        run: |
          terraform apply -input=false -auto-approve plan.file
        
