
name: Terraform CD

on:
  workflow_call:
    inputs:
      working-directory:
        description: 'Working Directory'
        required: true
        type: string
      tfplan-artifact-id:
        description: 'Terraform Plan Artifact ID'
        required: true
        type: string
    secrets:
      aws_access_key_id:
        description: 'AWS Access Key ID'
        required: true
      aws_secret_access_key:
        description: 'AWS Secret Access Key'
        required: true
      cloudflare_api_token:
        description: 'Cloudflare API Token'
        required: true

jobs:
  terraform-cd:
    runs-on: ubuntu-latest
    container: "missaelcorm/terratool:v0.10"
    env:
      TF_LOG: INFO
      AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key_id }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_access_key }}
      TF_VAR_cloudflare_api_token: ${{ secrets.cloudflare_api_token }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Terraform Plan Artifact
        uses: actions/download-artifact@master
        with:
          name: tfplan
          path: ${{ github.workspace }}/${{ inputs.working-directory }}

      - name: Terraform Init
        id: init
        working-directory: ${{ github.workspace }}/${{ inputs.working-directory }}
        run: |
          terraform init -input=false

      - name: Terraform Apply
        id: apply
        working-directory: ${{ github.workspace }}/${{ inputs.working-directory }}
        run: |
          terraform apply -input=false -auto-approve tfplan

  post-cd:
    runs-on: ubuntu-latest
    needs: terraform-cd
    steps:
      - name: Delete Terraform Plan Artifact
        run: |
          curl -L \
            -X DELETE \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository}}/actions/artifacts/${{ inputs.tfplan-artifact-id }}