name: Infrastructure as Code Security Scan

on:
  workflow_call:
    inputs:
      working-directory:
        description: 'Working Directory'
        required: true
        type: string
      environment:
        description: 'Environment'
        required: true
        type: string
    secrets:
      SLACK_WEBHOOK_URL:
        description: 'Slack Webhook Url'
        required: true
    outputs:
      tfsec-sarif-artifact-id:
        description: 'Terraform Security Scan Sarif Artifact ID'
        value: ${{ jobs.terraform-sec-scan.outputs.tfsec-sarif-artifact-id }}
      tfsec-json-artifact-id:
        description: 'Terraform Security Scan JSON Artifact ID'
        value: ${{ jobs.terraform-sec-scan.outputs.tfsec-json-artifact-id }}
    
jobs:
  terraform-sec-scan:
    runs-on: ubuntu-latest
    container: "missaelcorm/terratool:v0.10"
    outputs:
      tfsec-sarif-artifact-id: ${{ steps.tfsec-upload-sarif.outputs.artifact-id }}
      tfsec-json-artifact-id: ${{ steps.tfsec-upload-json.outputs.artifact-id }}
    env:
      ENVIRONMENT: ${{ inputs.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Terraform Security Check
        id: tfsec
        working-directory: ${{ github.workspace }}/${{ inputs.working-directory }}
        run: |
          tfsec . --minimum-severity MEDIUM -f lovely,json,sarif --out tfsec-report
        continue-on-error: true
        
      - name: Upload Sarif Terraform Security Report Artifact
        id: tfsec-upload-sarif
        uses: actions/upload-artifact@v4
        with:
          name: security_tfsec_${{ env.ENVIRONMENT }}_sarif_${{ github.sha }}
          path: ${{ github.workspace }}/${{ inputs.working-directory }}/tfsec-report.sarif.json
          if-no-files-found: error

      - name: Upload Sarif Terraform Security Report Artifact
        id: tfsec-upload-json
        uses: actions/upload-artifact@v4
        with:
          name: security_tfsec_${{ env.ENVIRONMENT }}_json_${{ github.sha }}
          path: ${{ github.workspace }}/${{ inputs.working-directory }}/tfsec-report.json
          if-no-files-found: error

      - name: Send notification to Slack
        uses: ./.github/actions/slack-notify
        if: always()
        with:
          job_name: 'Terraform Sec Scan'
          job_status: ${{ job.status }}
          github_workflow: ${{ github.workflow }}
          repo_name: ${{ github.repository }}
          branch_name: ${{ github.ref }}
          commit_sha: ${{ github.sha }}
          slack_channel: '#notifications'
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}

      # - name: Exit with failure if tfsec fails
      #   run: exit $([[ ${{ steps.tfsec.outcome }} == 'success' || ${{ steps.tfsec.outcome }} == 'skipped' ]] && echo 0 || echo 1)

      # Commenting out the upload to security tab as it is not supported by the GitHub for Organizations plan
      # - name: Upload to security tab
      #   uses: github/codeql-action/upload-sarif@v3
      #   with:
      #     sarif_file: ${{ github.workspace }}/${{ inputs.working-directory }}/tfsec-report.sarif.json
      #     category: Terraform Security
        