
name: Terraform CI

on:
  workflow_call:
    inputs:
      working-directory:
        description: 'Working Directory'
        required: true
        type: string
      aws_access_key_id:
        description: 'AWS Access Key ID'
        required: true
        type: string
      aws_secret_access_key:
        description: 'AWS Secret Access Key'
        required: true
        type: string
      cloudflare_api_token:
        description: 'Cloudflare API Token'
        required: true
        type: string

jobs:
  terraform-ci:
    runs-on: ubuntu-latest
    container: "missaelcorm/terratool:v0.10"
    env:
      TF_LOG: INFO
      AWS_ACCESS_KEY_ID: ${{ inputs.aws_access_key_id }}
      AWS_SECRET_ACCESS_KEY: ${{ inputs.aws_secret_access_key }}
      TF_VAR_cloudflare_api_token: ${{ inputs.cloudflare_api_token }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Terraform Plan Artifact
        uses: actions/download-artifact@master
        with:
          name: tfplan
          path: ${{ github.workspace }}/${{ inputs.working-directory }}

      - name: Terraform Init
        id: init
        working-directory: ${{ github.workspace }}/${{ inputs.working-directory }}
        run: |
          terraform init -input=false

      - name: Terraform Apply
        id: apply
        working-directory: ${{ github.workspace }}/${{ inputs.working-directory }}
        run: |
          terraform apply -input=false -auto-approve tfplan